import re
from typing import Any, Dict

import structlog

from star_organizer.display import console, print_error, print_success
from star_organizer.models import OUTPUT_FILE, OrganizedStarLists
from star_organizer.store import load_organized_stars

LOGGER = structlog.get_logger()

AWESOME_OUTPUT = "awesome-stars.md"


def _format_list_name(category: str) -> str:
    return category.replace("_", " ").title()


def generate_awesome_list(
    organized: OrganizedStarLists,
    output_path: str = AWESOME_OUTPUT,
    title: str = "Awesome Stars",
    description: str = "A curated list of my GitHub stars, organized by category.",
):
    if not organized:
        print_error("No organized data to export.")
        return ""

    lines = [
        f"# {title}",
        "",
        f"> {description}",
        "",
        "## Contents",
        "",
    ]

    sorted_cats = sorted(organized.items(), key=lambda x: x[0])

    for cat_name, _ in sorted_cats:
        display = _format_list_name(cat_name)
        anchor = re.sub(r"[^a-z0-9]+", "-", display.lower()).strip("-")
        lines.append(f"- [{display}](#{anchor})")

    lines.append("")

    total_repos = 0
    for cat_name, cat_data in sorted_cats:
        display = _format_list_name(cat_name)
        repos = cat_data.get("repos", [])
        desc = cat_data.get("description", "")

        lines.append(f"## {display}")
        if desc:
            lines.append(f"\n*{desc}*")
        lines.append("")

        if not repos:
            lines.append("*No repos yet.*")
            lines.append("")
            continue

        for repo in repos:
            if not isinstance(repo, dict):
                continue
            url = (repo.get("url", "") or "").strip()
            if not url:
                continue
            repo_desc = repo.get("description", "") or ""
            name = url.split("github.com/")[-1] if "github.com/" in url else url
            entry = f"- [{name}]({url})"
            if repo_desc:
                entry += f" - {repo_desc}"
            lines.append(entry)
            total_repos += 1

        lines.append("")

    lines.append("---")
    lines.append(
        f"*Generated by [star-organizer](https://github.com/shahshrey/star-organizer) "
        f"— {len(organized)} categories, {total_repos} repos*"
    )

    content = "\n".join(lines) + "\n"
    try:
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(content)
    except OSError as e:
        print_error(f"Failed to write awesome list to [bold]{output_path}[/bold]: {e}")
        return ""

    print_success(f"Awesome list saved to [bold]{output_path}[/bold] ({len(organized)} categories, {total_repos} repos)")
    return output_path


def run_awesome_export(output_file: str = OUTPUT_FILE, awesome_path: str = AWESOME_OUTPUT):
    organized = load_organized_stars(output_file)
    if not organized:
        print_error(f"No organized stars found at [bold]{output_file}[/bold]. Run the pipeline first.")
        return
    generate_awesome_list(organized, awesome_path)
